GO

IF NOT EXISTS (SELECT name FROM master.sys.databases WHERE name = N'Ajmera')
CREATE DATABASE Ajmera
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[BookMaster]') AND type in (N'U'))
CREATE TABLE BookMaster(
BookMasterID UNIQUEIDENTIFIER DEFAULT (NEWID()),
Name VARCHAR(100) NOT NULL,
AuthorName VARCHAR(100) NOT NULL,
IsActive Bit NOT NULL CONSTRAINT DF_BookMaster_IsActive_TRUE DEFAULT 1 ,
CreatedBy VARCHAR(100) NOT NULL,
CreatedDate DATETIME NOT NULL CONSTRAINT DF_BookMaster_CreatedDate_GETDATE DEFAULT GETDATE(),
ModifiedBy VARCHAR(100) NULL,
ModifiedDate DATETIME NULL,
CONSTRAINT PK_BookMaster PRIMARY KEY(BookMasterID)
)
GO