CREATE TABLE BookMaster(
BookMasterID UNIQUEIDENTIFIER DEFAULT (NEWID()),
Name VARCHAR(100) NOT NULL,
AuthorName VARCHAR(100) NOT NULL,
IsActive Bit NOT NULL CONSTRAINT DF_BookMaster_IsActive_TRUE DEFAULT 1 ,
CreatedBy VARCHAR(100) NOT NULL,
CreatedDate DATETIME NOT NULL CONSTRAINT DF_BookMaster_CreatedDate_GETDATE DEFAULT GETDATE(),
ModifiedBy VARCHAR(100) NULL,
ModifiedDate DATETIME NULL,
CONSTRAINT PK_BookMaster PRIMARY KEY(BookMasterID)
)