CREATE TABLE BookMaster(
BookMasterID UNIQUEIDENTIFIER PRIMARY KEY DEFAULT (NEWID()),
Name VARCHAR(100) NOT NULL,
AuthorName VARCHAR(100) NOT NULL,
IsActive Bit DEFAULT 1 NOT NULL,
CreatedBy VARCHAR(100) NOT NULL,
CreatedDate DATETIME DEFAULT GETDATE() NOT NULL,
ModifiedBy VARCHAR(100) NULL,
ModifiedDate DATETIME NULL
)